import { ClientSideSuspense } from "@liveblocks/react";
import { LiveObject } from "@liveblocks/client";
import { RoomProvider } from "liveblocks.config";
import Head from "next/head";
import CollaborativeEditor from "~/components/CollaborativeEditor";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto p-4">
        <RoomProvider
          id="type-together"
          initialStorage={{
            content: new LiveObject({ html: "", version: 0 }),
          }}
          initialPresence={{}}
        >
          <ClientSideSuspense fallback={<div>Loading…</div>}>{() => <CollaborativeEditor />}</ClientSideSuspense>
        </RoomProvider>
      </main>
    </>
  );
}
